# Generated by Django 5.1.5 on 2025-01-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('cpu', models.IntegerField()),
                ('mem', models.CharField(max_length=10)),
                ('disk', models.CharField(max_length=10)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incedent_type', models.CharField(max_length=20)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
                ('machine_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.machine')),
            ],
        ),
    ]
