# Generated by Django 5.1.5 on 2025-01-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='mem',
            new_name='memory',
        ),
    ]
